### ISSUE TITLE
How to make 2th example code?

### ISSUE THREAD

**Issue by leyafo** [greggagne/osc10e#2]
I have downloaded the source, follow the section 'Kernel Modules Overview' and compile the source use 'make'.
I get this error message:
```
make -C /lib/modules/4.9.0-8-amd64/build M=/root/osc10e/ch2 modules
make[1]: *** /lib/modules/4.9.0-8-amd64/build: No such file or directory.  Stop.
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2
```
I make the build directory manually.  and then get this message:
```
make -C /lib/modules/4.9.0-8-amd64/build M=/root/osc10e/ch2 modules
make[1]: Entering directory '/lib/modules/4.9.0-8-amd64/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/lib/modules/4.9.0-8-amd64/build'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2
```
The problem is the make cannot find the target, How can I rewrite my own makefile? I read the book, but no details to solve this problem.

**Comment by greggagne** [comment]
Are you running this using the Linux virtual machine we provide?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by leyafo** [comment]
Sorry, I use my own Debian.

**Comment by greggagne** [comment]
The kernel modules will work with the supplied Linux  VM. I suppose you could configure your Debian to make it work, but it requires installing a fair bit of additional software.

________________________________

**Comment by leyafo** [comment]
Thanks @greggagne. I've downloaded your Virtual machine and finished the 2th project exercises. 
Thanks for write this book.  It's a pleasure to read your book.

**Comment by greggagne** [comment]
Thank you!! Best of luck studying operating systems!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
